check for workflow dispatch status

diff --git a/.github/workflows/monolith_dev_workflow.yml b/.github/workflows/monolith_dev_workflow.yml
--- a/.github/workflows/monolith_dev_workflow.yml
+++ b/.github/workflows/monolith_dev_workflow.yml
@@ -16,12 +16,10 @@ env:
   IMAGE: "registry.gitlab.com/finestructure/pipeline-trigger:2.9.0"
   MAVEN_REPO_TOKEN: ${{ vars.MAVEN_REPO_TOKEN }}
   MAVEN_REPO_TOKEN_PASS: ${{ vars.MAVEN_REPO_TOKEN_PASS }}
-  GPG_PASS_PHRASE: ${{ secrets.GPG_PASS_PHRASE }}
-  RELEASE: ${{ vars.RELEASE }}
 
 jobs:
   build_semoss:
-    runs-on: self-hosted
+    runs-on: ubuntu-latest
     if: ${{ vars.RELEASE != 'TRUE' }}
     container:
       image: maven:3.8.6-jdk-8
@@ -31,17 +29,24 @@ jobs:
         run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV
       - name: Trigger semoss workflow
         run: |
-          curl -L \
+          RESPONSE=$(curl -L \
           -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/SEMOSS/semoss/actions/workflows/104712412/dispatches \
-          -d '{"ref":"dev"}'
+          -d "{\"ref\":\"dev\"}" -w "%{http_code}")
+
+          STATUS_CODE=$(echo $RESPONSE | tail -n1)
+          if [[ $STATUS_CODE != 200 || $STATUS_CODE !=204 ]]; then
+             echo "Failed the trigger worflow. HTTP Status: $STATUS_CODE"
+             exit 1
+          fi
+          echo "Successfully triggered workflow. HTTP Status: $STATUS_CODE"
 
   build_monolith_dev:
     needs: build_semoss
-    runs-on: self-hosted
+    runs-on: ubuntu-latest
     if: ${{ vars.RELEASE != 'TRUE'  && (github.event_name =='push' || github.event_name =='pull_request')  }}
     container:
       image: maven:3.8.6-jdk-8
@@ -49,10 +54,10 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      # - name: Set up JDK 8
-      #   uses: actions/setup-java@v3
-      #   with:
-      #     java-version: "8"
+      - name: Set up JDK 8
+        uses: actions/setup-java@v3
+        with:
+          java-version: "8"
 
       - name: Update and install openjfx
         run: |
@@ -76,7 +81,7 @@ jobs:
     #       path: target/monolith-${{ vars.VERSION }}-SNAPSHOT.war
 
   build_monolith_deploy:
-    runs-on: self-hosted
+    runs-on: ubuntu-latest
     container:
       image: maven:3.8.6-jdk-8
     if: ${{ vars.RELEASE != 'TRUE'  && github.event_name =='workflow_dispatch' }}
@@ -84,10 +89,10 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      # - name: Set up JDK 8
-      #   uses: actions/setup-java@v3
-      #   with:
-      #     java-version: "8"
+      - name: Set up JDK 8
+        uses: actions/setup-java@v3
+        with:
+          java-version: "8"
 
       - name: Update and install openjfx and gnupg2
         run: |
@@ -125,10 +130,10 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      # - name: Set up JDK 8
-      #   uses: actions/setup-java@v3
-      #   with:
-      #     java-version: "8"
+      - name: Set up JDK 8
+        uses: actions/setup-java@v3
+        with:
+          java-version: "8"
 
       - name: Update and install openjfx and gnupg2
         run: |
@@ -151,8 +156,8 @@ jobs:
       - name: Clear Maven repository after release
         run: rm -rf .m2/repository/org/semoss
 
-      # - name: Upload artifacts
-      #   uses: actions/upload-artifact@v3
-      #   with:
-      #     name: monolith-${{ vars.VERSION }}.war
-      #     path: target/monolith-${{ vars.VERSION }}.war
+      - name: Upload artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: monolith-${{ vars.VERSION }}.war
+          path: target/monolith-${{ vars.VERSION }}.war
